# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "7000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@ovandi.io
      PGADMIN_DEFAULT_PASSWORD: test 
    volumes:
      - "./docker-data/pgadmin:/var/lib/pgadmin" 
